import json

movies = [
    {
        "movie_id": 61,
        "title": "Kadaisi Ulaga Por",
        "genre": ["Action", "Sci-Fi", "Thriller"],
        "experience_type": "intense",
        "rating_percent": 82,
        "popularity_score": 0.85,
        "age_limit": 13,
        "netflix_url": "",
        "prime_url": "",
        "year": 2024,
        "poster": "https://upload.wikimedia.org/wikipedia/en/2/2c/Kadaisi_Ulaga_Por_poster.jpg",
        "synopsis": "Set in a dystopian future, a group of rebels fights against an oppressive regime in the last world war.",
        "quote": "The war isn't over until the last man stands. — In the face of extinction, resistance is survival.",
        "trailer": "j07X94M-2M0",
        "tags": ["modern", "dystopian"],
        "ottPlatforms": [],
        "director": "Hiphop Tamizha Adhi",
        "cast": "Hiphop Tamizha Adhi, Anagha, Natarajan Subramaniam",
        "keywords": "dystopia, war, futuristic, rebellion, chennai",
        "cinematographer": "Arjun Raja",
        "music": "Hiphop Tamizha",
        "writer": "Hiphop Tamizha Adhi"
    },
    {
        "movie_id": 62,
        "title": "Love Today",
        "genre": ["Comedy", "Romance", "Drama"],
        "experience_type": "fun",
        "rating_percent": 85,
        "popularity_score": 0.92,
        "age_limit": 13,
        "netflix_url": "https://www.netflix.com/title/81643110",
        "prime_url": "",
        "year": 2022,
        "poster": "https://upload.wikimedia.org/wikipedia/en/3/33/Love_Today_2022_poster.jpg",
        "synopsis": "A young couple is forced to swap their smartphones for 24 hours to prove their loyalty to each other before getting married.",
        "quote": "Trust is better than truth. — Sometimes the things we hide define the people we love.",
        "trailer": "n3W-9L_E99g",
        "tags": ["modern", "youth", "hit"],
        "ottPlatforms": [{"name": "Netflix", "url": "https://www.netflix.com/title/81643110"}],
        "director": "Pradeep Ranganathan",
        "cast": "Pradeep Ranganathan, Ivana, Sathyaraj, Yogi Babu",
        "keywords": "smartphone, trust, relationship, modern love, comedy",
        "cinematographer": "Dinesh Purushothaman",
        "music": "Yuvan Shankar Raja",
        "writer": "Pradeep Ranganathan"
    },
    {
        "movie_id": 63,
        "title": "The Goat Life (Aadujeevitham)",
        "genre": ["Adventure", "Drama", "Survival"],
        "experience_type": "emotional",
        "rating_percent": 88,
        "popularity_score": 0.89,
        "age_limit": 13,
        "netflix_url": "https://www.netflix.com/title/81643111",
        "prime_url": "",
        "year": 2024,
        "poster": "https://upload.wikimedia.org/wikipedia/en/e/ed/Aadujeevitham_poster.jpg",
        "synopsis": "Based on a true story, an Indian immigrant worker gets trapped in the deserts of Saudi Arabia as a goatherd.",
        "quote": "Freedom is the only destination. — Hope is the only light in the darkest desert.",
        "trailer": "L78RjT7NInY",
        "tags": ["biopic", "epic", "survival"],
        "ottPlatforms": [{"name": "Netflix", "url": "https://www.netflix.com/title/81643111"}],
        "director": "Blessy",
        "cast": "Prithviraj Sukumaran, Amala Paul, Jimmy Jean-Louis",
        "keywords": "desert, survival, immigrant, struggle, goats",
        "cinematographer": "Sunil K. S.",
        "music": "A. R. Rahman",
        "writer": "Blessy"
    },
    {
        "movie_id": 64,
        "title": "Lubber Pandhu",
        "genre": ["Drama", "Sports"],
        "experience_type": "fun",
        "rating_percent": 84,
        "popularity_score": 0.82,
        "age_limit": 0,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2024,
        "poster": "https://upload.wikimedia.org/wikipedia/en/7/7a/Lubber_Pandhu_poster.jpg",
        "synopsis": "A lighthearted sports drama centered around street cricket and the rivalry between two skilled players.",
        "quote": "Cricket is more than just a game; it's a heartbeat. — Every ball is a lesson, every hit is a triumph.",
        "trailer": "wL5b6V09L90",
        "tags": ["modern", "sports", "rural"],
        "ottPlatforms": [{"name": "Prime Video", "url": "https://www.amazon.com"}],
        "director": "Tamizharasan Pachamuthu",
        "cast": "Harish Kalyan, Attakathi Dinesh, Sanjana Krishnamoorthy",
        "keywords": "cricket, village, rivalry, rubber ball, friendship",
        "cinematographer": "Dinesh Purushothaman",
        "music": "Sean Roldan",
        "writer": "Tamizharasan Pachamuthu"
    },
    {
        "movie_id": 65,
        "title": "Garudan",
        "genre": ["Action", "Drama", "Thriller"],
        "experience_type": "intense",
        "rating_percent": 80,
        "popularity_score": 0.84,
        "age_limit": 13,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2024,
        "poster": "https://upload.wikimedia.org/wikipedia/en/5/5e/Garudan_2024_poster.jpg",
        "synopsis": "A loyal henchman finds himself caught between his childhood friend and a righteous man in a web of betrayal.",
        "quote": "Loyalty can be a cage, but truth is the key. — Justice waits for no man.",
        "trailer": "qX82ZgD-jN0",
        "tags": ["modern", "rural", "action"],
        "ottPlatforms": [{"name": "Prime Video", "url": "https://www.amazon.com"}],
        "director": "R. S. Durai Senthilkumar",
        "cast": "Soori, M. Sasikumar, Unni Mukundan",
        "keywords": "loyalty, betrayal, rural, justice, temple",
        "cinematographer": "Arthur A. Wilson",
        "music": "Yuvan Shankar Raja",
        "writer": "R. S. Durai Senthilkumar, Vetrimaaran"
    },
    {
        "movie_id": 66,
        "title": "Vaagai Sooda Vaa",
        "genre": ["Drama", "Period"],
        "experience_type": "emotional",
        "rating_percent": 86,
        "popularity_score": 0.75,
        "age_limit": 0,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2011,
        "poster": "https://upload.wikimedia.org/wikipedia/en/0/0e/Vaagai_Sooda_Vaa.jpg",
        "synopsis": "A young teacher goes to a remote village to educate children working in brick kilns, only to discover the harsh reality of their lives.",
        "quote": "Knowledge is the real wealth. — Education is the only weapon that can change the world.",
        "trailer": "Q_iA3L_sP1c",
        "tags": ["period", "social", "classic"],
        "ottPlatforms": [{"name": "Prime Video", "url": "https://www.amazon.com"}],
        "director": "A. Sarkunam",
        "cast": "Vimal, Iniya, K. Bhagyaraj",
        "keywords": "teacher, village, poverty, education, brick kiln",
        "cinematographer": "Om Prakash",
        "music": "M. Ghibran",
        "writer": "A. Sarkunam"
    },
    {
        "movie_id": 67,
        "title": "The Legend",
        "genre": ["Action", "Sci-Fi"],
        "experience_type": "fun",
        "rating_percent": 45,
        "popularity_score": 0.6,
        "age_limit": 13,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2022,
        "poster": "https://upload.wikimedia.org/wikipedia/en/a/a2/The_Legend_2022_poster.jpg",
        "synopsis": "A world-renowned scientist returns to his native village to help his community using his knowledge and technology.",
        "quote": "Service to humanity is the ultimate goal. — Wisdom is power.",
        "trailer": "8C6_e0xJ6c0",
        "tags": ["modern", "lavish"],
        "ottPlatforms": [{"name": "Disney+ Hotstar", "url": "https://www.hotstar.com"}],
        "director": "J.D.-Jerry",
        "cast": "Legend Saravanan, Urvashi Rautela, Vivek",
        "keywords": "scientist, village, medical, social service, technology",
        "cinematographer": "R. Rathnavelu",
        "music": "Harris Jayaraj",
        "writer": "J.D.-Jerry"
    },
    {
        "movie_id": 68,
        "title": "Aalavandhan",
        "genre": ["Action", "Psychological", "Thriller"],
        "experience_type": "intense",
        "rating_percent": 81,
        "popularity_score": 0.8,
        "age_limit": 18,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2001,
        "poster": "https://upload.wikimedia.org/wikipedia/en/e/e0/Aalavandhan.jpg",
        "synopsis": "A special forces officer must stop his mentally unstable twin brother from murdering his fiancée.",
        "quote": "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. — Shadows of the past never leave.",
        "trailer": "WnPu90GEWpU",
        "tags": ["cult", "classic", "dark"],
        "ottPlatforms": [{"name": "Prime Video", "url": "https://www.amazon.com"}],
        "director": "Suresh Krissna",
        "cast": "Kamal Haasan, Raveena Tandon, Manisha Koirala",
        "keywords": "twins, psychological, hallucination, commando, prison break",
        "cinematographer": "S. Tirru",
        "music": "Shankar-Ehsaan-Loy",
        "writer": "Kamal Haasan"
    },
    {
        "movie_id": 69,
        "title": "Virumaandi",
        "genre": ["Action", "Drama"],
        "experience_type": "intense",
        "rating_percent": 87,
        "popularity_score": 0.85,
        "age_limit": 18,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2004,
        "poster": "https://upload.wikimedia.org/wikipedia/en/e/ed/Virumaandi.jpg",
        "synopsis": "A non-linear narrative exploring the lives of two prisoners and the events that led to their incarceration, questioning the death penalty.",
        "quote": "An eye for an eye will make the whole world blind. — Truth is rarely pure and never simple.",
        "trailer": "RVN_g9XYUsY",
        "tags": ["cult", "classic", "social"],
        "ottPlatforms": [{"name": "Prime Video", "url": "https://www.amazon.com"}],
        "director": "Kamal Haasan",
        "cast": "Kamal Haasan, Abhirami, Pasupathy",
        "keywords": "non-linear, village, revenge, death penalty, jallikattu",
        "cinematographer": "Keshav Prakash",
        "music": "Ilaiyaraaja",
        "writer": "Kamal Haasan"
    },
    {
        "movie_id": 70,
        "title": "Thuppakki",
        "genre": ["Action", "Thriller"],
        "experience_type": "intense",
        "rating_percent": 88,
        "popularity_score": 0.95,
        "age_limit": 13,
        "netflix_url": "",
        "prime_url": "https://www.amazon.com",
        "year": 2012,
        "poster": "https://upload.wikimedia.org/wikipedia/en/0/05/Thuppakki_poster.jpg",
        "synopsis": "An army captain on vacation in Mumbai intercepts a terrorist plot and sets out to dismantle the sleeper cells in the city.",
        "quote": "I am waiting! — One man's war against terror.",
        "trailer": "wP1M_s4_290",
        "tags": ["blockbuster", "modern", "army"],
        "ottPlatforms": [{"name": "Disney+ Hotstar", "url": "https://www.hotstar.com"}],
        "director": "A. R. Murugadoss",
        "cast": "Vijay, Kajal Aggarwal, Sathyan",
        "keywords": "army, sleeper cell, mumbai, terrorism, intelligence",
        "cinematographer": "Santosh Sivan",
        "music": "Harris Jayaraj",
        "writer": "A. R. Murugadoss"
    }
]

with open('d:/univibe/data/newMovies.json', 'w') as f:
    json.dump(movies, f, indent=4)
